name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: check repository
      - uses: actions/checkout@v2 

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '18'      
      - name: Save key
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}

        run: echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
      - name: node version
        run: node -v
      - name: where 
        run: pwd
      - name: list
        run: ls -l
      - name: Build
        run: |
          npm install
          npm run build
      - name: list deploy
        run: ls -l dist
      - name: Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
        run: |
          echo "Hostname: $HOSTNAME"
          echo "user: $USER_NAME"
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -i private_key dist ${USER_NAME}@${HOSTNAME}:wirl/
          
